version: 2

builds:
  - main: .
    binary: frond
    ldflags:
      - -s -w -X github.com/nvandessel/frond/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - repository:
      owner: nvandessel
      name: homebrew-frond
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/nvandessel/frond
    description: Agent-first CLI for managing stacked PRs
    license: Apache-2.0
    install: |
      bin.install "frond"
    test: |
      system "#{bin}/frond", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
