version: 2

builds:
  - main: .
    binary: frond
    ldflags:
      - -s -w -X github.com/nvandessel/frond/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

homebrew_casks:
  - repository:
      owner: nvandessel
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/nvandessel/frond
    description: Agent-first CLI for managing stacked PRs
    license: Apache-2.0
    binaries:
      - frond

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  extra_files:
    - glob: .floop/packs/nvandessel-frond-*.fpack
      name_template: nvandessel-frond.fpack
