name: Bug Report
description: Report a bug in frond
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Run `frond new feature-branch`
        2. Run `frond push`
        3. See error
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system details
      placeholder: |
        - OS: Linux / macOS / Windows
        - Go version: 1.25.x
        - frond version: 0.1.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error messages or log output
      render: shell
